### ISSUE TITLE
Enable tags for coq/coq PR.

### ISSUE THREAD

**Issue by ejgallego** [coq/roadmaps#5]
Hi, reporting here as I don't think there's a better place.

It would be nice if we could tag the PRs in coq/coq as to organize things a bit better. A preliminary set of tags could be `8.6`, `8.7`, `review`, `inprogress`, etc..

**Comment by gares** [comment]
Very good idea, let me add a few of those (I guess I've the right)

**Comment by gares** [comment]
I've added the 4 tags you  suggested, but I guess there is room for more.  All ears

**Comment by ejgallego** [comment]
Oh cool Enrico, thanks!

**Comment by ejgallego** [comment]
A couple of remarks:
- It seems thou that labels can only be set by project owners, pity, it would be good if at least the PR submitter could add/remove labels too, sadly it seems you need write access for that :S
- Github also provides milestones; maybe there are also useful to keep track of the PRs needing merge for a particular release?
- An 8.5 (pl2?) label may be useful too.

**Comment by gares** [comment]
Hum, the github archive is just a mirror, so giving a wider audience "write" access should not be a problem... I'll ask what people think

**Comment by ejgallego** [comment]
IMO giving access to every person reporting a PR is too much of a hassle; I guess the release managers can adjust tags. Is a pity thou because GitLab indeed has a "reporter" role that fits exactly this purpose.

**Comment by ejgallego** [comment]
Another couple of useful tags here could "rejected" and "changes_requested" ?? Oh, well, this last one can be improved...

**Comment by maximedenes** [comment]
I guess most of this is in place now (up to github limitations). So closing.
